### ISSUE TITLE
multi modules beginners question

### ISSUE THREAD

**Issue by bouteillerAlan** [troydm/xmonad-dbus#5]
Hello first of all thank you for this extension, it saved me a lot of time!

I have a "beginner" question : I want to made 3 different modules in polybar for the window title, the workspace, etc..

So _stupidly_ I do a bash script like this : 
```sh
#!/bin/sh

# get the result -> %{F#54a0ff}%{F-} %{F#c8d6e5}%{F-} : Spacing Tall : %{F#00ff00} Alacritty %{F-}
IN=$(xmonad-dbus)

# replace all space by + -> %{F#54a0ff}%{F-}+%{F#c8d6e5}%{F-}+:+Spacing+Tall+:+%{F#00ff00}+Alacritty+%{F-}
string=$(echo $IN | tr " " "+")

# transform in array -> (%{F#54a0ff}%{F-}+%{F#c8d6e5}%{F-}+ +Spacing+Tall+ +%{F#00ff00}+Alacritty+%{F-})
arrIN=(${string//:/ })

# echo the workspace and remove not necessary characters -> %{F#54a0ff}%{F-} %{F#c8d6e5}%{F-}
echo $(echo ${arrIN[0]} | tr "+" " ")
```
and call it like that : 
```
[module/xmonad]
type = custom/script
exec = ~/.config/polybar/scripts/workspace.sh
tail = true
interval = 1
```
But this not work.

So I see the `xmonad-dbus` command have result only if something append in XMonad.

I test too something like that : 
```
-- in my script
IN=$1

-- in the module
exec = ~/.config/polybar/scripts/workspace.sh xmonad-dbus
```

Any idea to do that ?

**Comment by troydm** [comment]
@bouteillerAlan actually I'm no expert myself but what I can suggest you is to customize the ppLayout from xmonad config instead of bash script, you can see how I do it inside my own config
https://github.com/troydm/dotcentral/blob/master/configurations/troypc/xmonad/xmonad.hs
https://github.com/troydm/dotcentral/blob/master/configurations/troypc/polybar/config

**Comment by bouteillerAlan** [comment]
work for me thanks =)
